global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Spring Boot applications metrics
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names:
          - 'spring-app'
        type: 'A'
        port: 8080
        refresh_interval: 10s

  # HAProxy metrics (if HAProxy exporter is configured)
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8404']
    metrics_path: '/stats;csv'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 