spring:
  application:
    name: haproxy-demo

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  jetty:
    threads:
      max: 200
      min: 10
    accesslog:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      instance: ${HOSTNAME:localhost}

logging:
  level:
    root: INFO
    com.example.haproxy: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

info:
  app:
    name: ${spring.application.name}
    version: '@project.version@'
    description: '@project.description@' 