spring:
  profiles: prod

server:
  jetty:
    threads:
      max: 500
      min: 50

logging:
  level:
    root: WARN
    com.example.haproxy: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoint:
    health:
      show-details: when-authorized 